spring.config.import=optional:file:./config.ini[.properties]

spring.application.name=org.agty.drive

spring.datasource.url=jdbc:postgresql://${db.agtydrive.server:localhost}:${db.agtydrive.port:5432}/${db.agtydrive.database:agty_drive}
spring.datasource.username=${db.agtydrive.user:postgres}
spring.datasource.password=${db.agtydrive.password:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=${upload.max_file_size:1024MB}
spring.servlet.multipart.max-request-size=${upload.max_request_size:1024MB}

server.servlet.session.timeout=${session.timeout_minutes:43200}m
server.servlet.session.cookie.max-age=${session.cookie_max_age_minutes:43200}m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=agdrv_sessions

spring.flyway.enabled=false
